spring:
  application:
    name: docparser
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY}
      model: gemini-2.0-flash

  mail:
#    host: smtp.gmail.com
#    port: 587
    host: imap.gmail.com
    port: 993
    username: ${EMAIL_NAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        store:
          protocol: imaps
        imaps:
          ssl:
            enable: true
server:
  port: 3040
openai:
  api:
    key: ${OPEN_API_KEY}